booking/urls.py
from django.urls import path

from booking.views import *

app_name = 'booking'

urlpatterns = [
    path('book/<int:pk>', book_room, name='book'),
    path('delete-booking/', delete_booking, name='delete_booking'),
    path('check-available-rooms/', check_available_rooms_by_number, name='check_available_rooms_by_number'),
]

customer/urls.py
from django.urls import path
from django.views.generic import TemplateView

from customer.views import *

app_name = 'customer'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('dashboard/', customer_dashboard, name='dashboard'),

]

django_hotel_booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from rooms.views import room_type_list, index

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('', index, name='home'),

                  path('customer/', include('customer.urls')),
                  path('booking/', include('booking.urls')),
                  path('payment/', include('payment.urls')),
                  path('rooms/', include('rooms.urls')),
                  path('rooms/', room_type_list, name='rooms'),
                  path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
                  path('contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
                  path('services/', TemplateView.as_view(template_name='services.html'), name='services'),
                  path('cart/', TemplateView.as_view(template_name='cart.html'), name='cart'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from .views import *

app_name = 'payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('charge/', charge, name='charge'),
]

rooms/urls.py
from django.urls import path

from rooms.views import check_available_rooms_by_type

app_name = 'rooms'

urlpatterns = [
    path('check-available-rooms-by-type/<int:pk>', check_available_rooms_by_type, name='check_available_rooms_by_type')
]

rooms/models.py
from django.db import models

room_type_choices = (
    ('suite', 'Suite Room'),
    ('standard', 'Standard Room'),
    ('family', 'Family Room'),
    ('deluxe', 'Deluxe Room'),
    ('luxury', 'Luxury Room'),
    ('superior', 'Superior Room'),
)


class RoomType(models.Model):
    room_type = models.CharField(max_length=32, choices=room_type_choices)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    maximum_capacity = models.IntegerField()
    size = models.IntegerField()
    view = models.CharField(max_length=32)
    bed_number = models.IntegerField()
    ratings = models.DecimalField(max_digits=2, decimal_places=1)

    def __str__(self):
        return self.room_type.capitalize()


class Room(models.Model):
    room_no = models.CharField(max_length=10)
    room_type = models.ForeignKey(RoomType, related_name='rooms', on_delete=models.CASCADE)
    available = models.BooleanField()

    def __str__(self):
        return f'{self.room_type} {self.room_no}'

rooms/views.py
from django.shortcuts import render

from booking.models import Booking
from rooms.models import RoomType, Room


def room_type_list(request):
    room_types = RoomType.objects.all()

    return render(request, 'rooms.html', {'room_types': room_types})


def index(request):
    room_types = RoomType.objects.all()

    bookings = Booking.objects.all()

    for booking in bookings:
        booking.days_remaining()

    return render(request, 'index.html', {'room_types': room_types})


def check_available_rooms_by_type(request, pk):
    available_rooms = Room.objects.filter(available=True, room_type_id=pk)

    return render(request, 'available_rooms.html', {'available_rooms': available_rooms})

templates/available_rooms.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    {% include 'partials/breadcrumb.html' with title='Available Rooms' %}


    <section class="ftco-section bg-light ftco-no-pt ftco-no-pb">
        <div class="container-fluid px-md-0">
            <div class="row no-gutters">
                {% if available_rooms %}

                    {% for available_room in available_rooms %}


                        <div class="col-lg-6">
                            <div class="room-wrap d-md-flex">
                                <a href="#" class="img"
                                   style="background-image: url({% static 'base/' %}images/room-1.jpg);"></a>
                                <div class="half left-arrow d-flex align-items-center">
                                    <div class="text p-4 p-xl-5 text-center">
                                        <p class="star mb-0"><span class="fa fa-star"></span><span
                                                class="fa fa-star"></span><span class="fa fa-star"></span><span
                                                class="fa fa-star"></span><span class="fa fa-star"></span></p>
                                        <p class="mb-0"><span
                                                class="price mr-1">${{ available_room.room_type.price }}</span> <span
                                                class="per">per night</span></p>
                                        <h3 class="mb-3"><a
                                                href="rooms.html"><span>Room No: </span>{{ available_room.room_no }}</a>
                                        </h3>
                                        <ul class="list-accomodation">
                                            <li><span>Room Type:</span> {{ available_room.room_type }}</li>
                                            <li><span>Max:</span> {{ available_room.room_type.maximum_capacity }}
                                                Persons
                                            </li>
                                            <li><span>Size:</span> {{ available_room.room_type.size }} m2</li>
                                            <li><span>View:</span> {{ available_room.room_type.view }}</li>
                                            <li><span>Bed:</span> {{ available_room.room_type.bed_number }}</li>
                                        </ul>
                                        <p class="pt-1"><a href="{% url 'booking:book' available_room.pk %}"
                                                           class="btn-custom px-3 py-2">Book This Room <span
                                                class="icon-long-arrow-right"></span></a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="text-center">
                        <h1>No rooms available! Please check back later!</h1>

                    </div>
                {% endif %}
                {#    			<div class="col-lg-6">#}
                {#    				<div class="room-wrap d-md-flex">#}
                {#    					<a href="#" class="img" style="background-image: url({% js 'base/' %}images/room-2.jpg);"></a>#}
                {#    					<div class="half left-arrow d-flex align-items-center">#}
                {#    						<div class="text p-4 p-xl-5 text-center">#}
                {#    							<p class="star mb-0"><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span></p>#}
                {#    							<p class="mb-0"><span class="price mr-1">$120.00</span> <span class="per">per night</span></p>#}
                {#	    						<h3 class="mb-3"><a href="rooms.html">Standard Room</a></h3>#}
                {#									<ul class="list-accomodation">#}
                {#	    							<li><span>Max:</span> 3 Persons</li>#}
                {#	    							<li><span>Size:</span> 45 m2</li>#}
                {#	    							<li><span>View:</span> Sea View</li>#}
                {#	    							<li><span>Bed:</span> 1</li>#}
                {#	    						</ul>#}
                {#	    						<p class="pt-1"><a href="room-single.html" class="btn-custom px-3 py-2">View Room Details <span class="icon-long-arrow-right"></span></a></p>#}
                {#    						</div>#}
                {#    					</div>#}
                {#    				</div>#}
                {#    			</div>#}
                {##}
                {#    			<div class="col-lg-6">#}
                {#    				<div class="room-wrap d-md-flex">#}
                {#    					<a href="#" class="img order-md-last" style="background-image: url({% js 'base/' %}images/room-3.jpg);"></a>#}
                {#    					<div class="half right-arrow d-flex align-items-center">#}
                {#    						<div class="text p-4 p-xl-5 text-center">#}
                {#    							<p class="star mb-0"><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span></p>#}
                {#    							<p class="mb-0"><span class="price mr-1">$120.00</span> <span class="per">per night</span></p>#}
                {#	    						<h3 class="mb-3"><a href="rooms.html">Family Room</a></h3>#}
                {#									<ul class="list-accomodation">#}
                {#	    							<li><span>Max:</span> 3 Persons</li>#}
                {#	    							<li><span>Size:</span> 45 m2</li>#}
                {#	    							<li><span>View:</span> Sea View</li>#}
                {#	    							<li><span>Bed:</span> 1</li>#}
                {#	    						</ul>#}
                {#	    						<p class="pt-1"><a href="room-single.html" class="btn-custom px-3 py-2">View Room Details <span class="icon-long-arrow-right"></span></a></p>#}
                {#    						</div>#}
                {#    					</div>#}
                {#    				</div>#}
                {#    			</div>#}
                {#    			<div class="col-lg-6">#}
                {#    				<div class="room-wrap d-md-flex">#}
                {#    					<a href="#" class="img order-md-last" style="background-image: url({% js 'base/' %}images/room-4.jpg);"></a>#}
                {#    					<div class="half right-arrow d-flex align-items-center">#}
                {#    						<div class="text p-4 p-xl-5 text-center">#}
                {#    							<p class="star mb-0"><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span></p>#}
                {#    							<p class="mb-0"><span class="price mr-1">$120.00</span> <span class="per">per night</span></p>#}
                {#	    						<h3 class="mb-3"><a href="rooms.html">Deluxe Room</a></h3>#}
                {#									<ul class="list-accomodation">#}
                {#	    							<li><span>Max:</span> 3 Persons</li>#}
                {#	    							<li><span>Size:</span> 45 m2</li>#}
                {#	    							<li><span>View:</span> Sea View</li>#}
                {#	    							<li><span>Bed:</span> 1</li>#}
                {#	    						</ul>#}
                {#	    						<p class="pt-1"><a href="room-single.html" class="btn-custom px-3 py-2">View Room Details <span class="icon-long-arrow-right"></span></a></p>#}
                {#    						</div>#}
                {#    					</div>#}
                {#    				</div>#}
                {#    			</div>#}
                {##}
                {#    			<div class="col-lg-6">#}
                {#    				<div class="room-wrap d-md-flex">#}
                {#    					<a href="#" class="img" style="background-image: url({% js 'base/' %}images/room-5.jpg);"></a>#}
                {#    					<div class="half left-arrow d-flex align-items-center">#}
                {#    						<div class="text p-4 p-xl-5 text-center">#}
                {#    							<p class="star mb-0"><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span></p>#}
                {#	    						<h3 class="mb-3"><a href="rooms.html">Luxury Room</a></h3>#}
                {#									<ul class="list-accomodation">#}
                {#	    							<li><span>Max:</span> 3 Persons</li>#}
                {#	    							<li><span>Size:</span> 45 m2</li>#}
                {#	    							<li><span>View:</span> Sea View</li>#}
                {#	    							<li><span>Bed:</span> 1</li>#}
                {#	    						</ul>#}
                {#	    						<p class="pt-1"><a href="room-single.html" class="btn-custom px-3 py-2">View Room Details <span class="icon-long-arrow-right"></span></a></p>#}
                {#    						</div>#}
                {#    					</div>#}
                {#    				</div>#}
                {#    			</div>#}
                {#    			<div class="col-lg-6">#}
                {#    				<div class="room-wrap d-md-flex">#}
                {#    					<a href="#" class="img" style="background-image: url({% js 'base/' %}images/room-6.jpg);"></a>#}
                {#    					<div class="half left-arrow d-flex align-items-center">#}
                {#    						<div class="text p-4 p-xl-5 text-center">#}
                {#    							<p class="star mb-0"><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span><span class="fa fa-star"></span></p>#}
                {#	    						<h3 class="mb-3"><a href="rooms.html">Superior Room</a></h3>#}
                {#									<ul class="list-accomodation">#}
                {#	    							<li><span>Max:</span> 3 Persons</li>#}
                {#	    							<li><span>Size:</span> 45 m2</li>#}
                {#	    							<li><span>View:</span> Sea View</li>#}
                {#	    							<li><span>Bed:</span> 1</li>#}
                {#	    						</ul>#}
                {#	    						<p class="pt-1"><a href="room-single.html" class="btn-custom px-3 py-2">View Room Details <span class="icon-long-arrow-right"></span></a></p>#}
                {#    						</div>#}
                {#    					</div>#}
                {#    				</div>#}
                {#    			</div>#}
            </div>
        </div>
    </section>

{% endblock content %}

templates/dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}


    <section class="ftco-section bg-light ftco-no-pt ftco-no-pb">
        <div class="container-fluid">
            <div class="row navbar-expand-md">
                <nav class="col-md-3 col-lg-2 bg-dark navbar-collapse collapse sidebar" id="sidenav"
                     style="align-items: flex-start;">

                    <div class="sidebar-sticky flex-column w-100 mt-1">
                        <h2 class="text-light">Dashboard</h2>
                        <hr>
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'customer:dashboard' %}">
                                    <span data-feather="home"></span> View Bookings <span
                                        class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'home' %}">
                                    <span data-feather="file"></span> Add Bookings
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                    <h2>Bookings</h2>
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>Booking ID</th>
                                <th>Room No</th>
                                <th>Price</th>
                                <th>Paid</th>
                                <th>Check in date</th>
                                <th>Check out date</th>
                                <th>Days remaining</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for booking in bookings %}
                                <tr>
                                    <td>{{ booking.pk }}</td>
                                    <td>{{ booking.room.room_no }}</td>
                                    <td>{{ booking.booking_price }}</td>
                                    <td>{% if booking.paid %}
                                        Yes
                                    {% else %}
                                        No
                                    {% endif %} </td>
                                    <td>{{ booking.check_in_date }}</td>
                                    <td>{{ booking.check_out_date }}</td>
                                    <td>{{ booking.days_remaining }}</td>
                                    <td>{% if booking.paid %}

                                    {% else %}
                                        <form action="{% url 'payment:checkout' %}" method="post">
                                            {% csrf_token %}

                                            <input name="amount" value="{{ booking.booking_price }}" hidden>
                                            <input name="booking-pk" value="{{ booking.pk }}" hidden>
                                            <input type="submit" class="btn btn-primary" value="Pay">
                                        </form>
                                        <form action="{% url 'booking:delete_booking' %}" method="post">
                                            {% csrf_token %}
                                            <input name="booking-pk" value="{{ booking.pk }}" hidden>

                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        </form>
                                    {% endif %} </td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>
                </main>
            </div>
        </div>
    </section>
{% endblock content %}

templates/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    {% include 'partials/breadcrumb.html' with title='Login' %}


    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row no-gutters">
            </div>
            <div class="col-md-12">
                <div class="wrapper">
                    <div class="row no-gutters">
                        <div class="col-lg-8 col-md-7 d-flex align-items-stretch">
                            <div class="contact-wrap w-100 p-md-5 p-4">
                                <h3 class="mb-4">Login</h3>
                                <div id="form-message-warning" class="mb-4"></div>
                                <div id="form-message-success" class="mb-4">
                                    Login successful, you will be redirected shortly!
                                </div>
                                <form method="POST" id="contactForm" name="contactForm" class="contactForm"
                                      action="{% url 'customer:login' %}?next={{ next_page }}">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">

                                    <div class="row">

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label class="label" for="username">Username</label>
                                                <input type="text" class="form-control" name="username" id="username"
                                                       placeholder="Username">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label class="label" for="password">Password</label>
                                                <input type="password" class="form-control" name="password"
                                                       id="password" placeholder="password">
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input type="submit" value="Login" class="btn btn-primary">
                                                <div class="submitting">
                                                    Don't have an account? Register <a
                                                        href="{% url 'customer:register' %}">here</a>!
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

{% endblock content %}

templates/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    {% include 'partials/breadcrumb.html' with title='Register' %}


    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row no-gutters">


                <div class="col-md-12">
                    <div class="wrapper">
                        <div class="row no-gutters">
                            <div class="col-lg-8 col-md-7 d-flex align-items-stretch">
                                <div class="contact-wrap w-100 p-md-5 p-4">
                                    <h3 class="mb-4">Register</h3>

                                    <div id="form-message-warning" class="mb-4">
                                        <ul>
                                            {% for field in user_form %}
                                                {% if field.errors %}
                                                    <li>
                                                        {{ field.label }}
                                                        <ul class="errorlist">
                                                            {% for error in field.errors %}
                                                                <li>{{ error }}</li>
                                                            {% endfor %}
                                                        </ul>
                                                    </li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>

                                        <ul>
                                            {% for field in customer_form %}
                                                {% if field.errors %}
                                                    <li>
                                                        {{ field.label }}
                                                        <ul class="errorlist">
                                                            {% for error in field.errors %}
                                                                <li>{{ error }}</li>
                                                            {% endfor %}
                                                        </ul>
                                                    </li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div id="form-message-success" class="mb-4">
                                    </div>
                                    <form method="POST" id="contactForm" name="contactForm" class="contactForm"
                                          action="{% url 'customer:register' %}">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="label" for="first_name">First Name</label>
                                                    <input type="text" class="form-control" name="first_name"
                                                           id="first_name" placeholder="First Name">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="label" for="last_name">Last Name</label>
                                                    <input type="text" class="form-control" name="last_name"
                                                           id="last_name" placeholder="Last Name">
                                                </div>

                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="nid_no">NID Number</label>
                                                    <input type="text" class="form-control" name="nid_no"
                                                           id="nid_no" placeholder="NID Number">
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="passport_no">Passport Number</label>
                                                    <input type="text" class="form-control" name="passport_no"
                                                           id="passport_no" placeholder="Passport Number">
                                                </div>
                                            </div>

                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="photo">Photo</label>
                                                    <input type="file" class="form-control" name="photo"
                                                           id="photo" placeholder="Photo">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="phone_no">Phone Number</label>
                                                    <input type="text" class="form-control" name="phone_no"
                                                           id="phone_no"
                                                           placeholder="Phone No">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="email">Email Address</label>
                                                    <input type="email" class="form-control" name="email" id="email"
                                                           placeholder="Email">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="username">Username</label>
                                                    <input type="text" class="form-control" name="username"
                                                           id="username" placeholder="Username">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="label" for="password">Password</label>
                                                    <input type="password" class="form-control" name="password"
                                                           id="password" placeholder="Password">
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <input type="submit" value="Register" class="btn btn-primary">
                                                    <div class="submitting">
                                                        Already have an account? Login <a href="#">here</a>!

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}