customer/urls.py
from django.urls import path
from django.views.generic import TemplateView

from customer.views import *

app_name = 'customer'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('dashboard/', customer_dashboard, name='dashboard'),

]

django_hotel_booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from rooms.views import room_type_list, index

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('', index, name='home'),

                  path('customer/', include('customer.urls')),
                  path('booking/', include('booking.urls')),
                  path('payment/', include('payment.urls')),
                  path('rooms/', include('rooms.urls')),
                  path('rooms/', room_type_list, name='rooms'),
                  path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
                  path('contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
                  path('services/', TemplateView.as_view(template_name='services.html'), name='services'),
                  path('cart/', TemplateView.as_view(template_name='cart.html'), name='cart'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from .views import *

app_name = 'payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('charge/', charge, name='charge'),
]

rooms/urls.py
from django.urls import path

from rooms.views import check_available_rooms_by_type

app_name = 'rooms'

urlpatterns = [
    path('check-available-rooms-by-type/<int:pk>', check_available_rooms_by_type, name='check_available_rooms_by_type')
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from booking.models import Booking

stripe.api_key = settings.STRIPE_SECRET_KEY


def checkout(request):
    if request.method == 'POST':
        amount = request.POST['amount']
        booking_pk = request.POST['booking-pk']

        context = {'amount': amount,
                   'booking_pk': booking_pk,
                   }
        return render(request, 'payment/checkout.html', context)
    else:
        return redirect(reverse('home'))


def charge(request):
    if request.method == 'POST':

        print('Data:', request.POST)

        booking_pk = request.POST['booking-pk']

        amount = int(float(request.POST['amount']))

        booking = get_object_or_404(Booking, pk=booking_pk)

        if not booking.paid:
            customer = stripe.Customer.create(
                email=request.POST['email'],
                name=request.POST['name'],
                source=request.POST['stripeToken']
            )

            charge = stripe.Charge.create(
                customer=customer,
                amount=amount * 100,
                currency='usd',
                description=f'Payment for booking: {booking}',

            )

            booking.paid = True
            booking.booked = True

            booking.room.available = False
            booking.room.save(force_update=True)
            booking.save(force_update=True)

            # context = {
            #     'booking': booking,
            #     'amount': amount,
            # }
            # return render(request, 'payment/charge.html', context)

        return redirect(reverse('customer:dashboard'))
    else:
        return redirect(reverse('home'))

payment/templates/payment/charge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Refresh" content="5" ; url="{% url 'customer:dashboard' %}"/>

    <title>Payment Successful</title>
</head>
<body>
Payment successful for booking {{ booking }}.
${{ amount }} has been charged!

You will be redirected to the dashboard shortly. If doesn't automatically redirects, click <a
        href="{% url 'customer:dashboard' %}">here</a>.
</body>
</html>

payment/templates/payment/checkout.html
<html>

{% load static %}
<head>
    <title>Checkout</title>
    <style type="text/css" href="{% static 'payment/css/stripe.css' %}"></style>


    <script src="https://js.stripe.com/v3/"></script>

    <style>
        body {
            margin: 50px auto;
            width: 600px;
        }

        /* CSS for Credit Card Payment form */
        .credit-card-box .panel-title {
            display: inline;
            font-weight: bold;
        }

        .credit-card-box .form-control.error {
            border-color: red;
            outline: 0;
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(255, 0, 0, 0.6);
        }

        .credit-card-box label.error {
            font-weight: bold;
            color: red;
            padding: 2px 8px;
            margin-top: 2px;
        }

        .credit-card-box .payment-errors {
            font-weight: bold;
            color: red;
            padding: 2px 8px;
            margin-top: 2px;
        }

        .credit-card-box label {
            display: block;
        }

        /* The old "center div vertically" hack */
        .credit-card-box .display-table {
            display: table;
        }

        .credit-card-box .display-tr {
            display: table-row;
        }

        .credit-card-box .display-td {
            display: table-cell;
            vertical-align: middle;
            width: 50%;
        }

        /* Just looks nicer */
        .credit-card-box .panel-heading img {
            min-width: 180px;
        }
    </style>

</head>

<body>


<div id="container">
    <div class="column-6">
        <div id="left-wrapper">
            <h1>Payment</h1>
        </div>
        <div style="clear:left"></div>
        <hr>
        <div class="column-6">
            <h3>Amount: {{ amount }} USD</h3>
        </div>
        <!-- Add form here -->
        <form action="{% url 'payment:charge' %}" method="post" id="payment-form">
            {% csrf_token %}
            {#            <div class="form-field-12">#}
            {#                <label for="amount">Choose Amount:</label>#}
            {#                <br>#}
            {#                <br>#}
            {#                <select required name="amount" id="amount">#}
            {#                    <option selected value="5">$5 --- Here's a coffee, on me :)</option>#}
            {#                    <option value="10">$10 --- You helped me, so I am going to help you</option>#}
            {#                    <option value="25">$25 --- I love your channel!</option>#}
            {#                </select>#}
            {#            </div>#}

          <div class="form-field-6">
                <input required type="text" name="booking-pk" value="{{ booking_pk }}" hidden>
            </div>

            <div class="form-field-6">
                <input required type="text" name="amount" value="{{ amount }}" hidden>
            </div>

            <div class="form-field-6">
                <input required type="text" name="email" placeholder="Email"
                       {% if user.is_authenticated %}value="{{ user.email }}" {% endif %}>
            </div>

            <div class="form-field-6">
                <input required type="text" name="name" placeholder="Name"
                       {% if user.is_authenticated %}value="{{ user.customer }}" {% endif %}>
            </div>

            <div class="form-row">
                <label for="card-element">
                    Credit or debit card
                </label>
                <div id="card-element">
                    <!-- A Stripe Element will be inserted here. -->
                </div>

                <!-- Used to display form errors. -->
                <div id="card-errors" role="alert"></div>
            </div>

            <div style="clear:left"></div>
            <hr>

            <input class="btn-primary" style="background-color:#10a195" type="submit" value="Pay"
                   name="">

        </form>


    </div>
</div>
</div>


<script src="{% static 'payment/js/stripe.js' %}"></script>

</body>
</html>